import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class StudentRegistryForm extends JFrame {
    
    /**
     * Creates new form StudentRegistryForm
     */
    
    // variable for filling combobox data
    private final JComboBox<String> studentClassesComboboxmodel = new JComboBox<>();

    // method for filling the combobox with csv file data
    private JComboBox<String> loadDataFromFile(){
        String fileName = "class_data.csv";
        
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
        // Read the first line to check if the file has data
        String line ;
        br.readLine();
        while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                // add each line to the variable
                studentClassesComboboxmodel.addItem(data[0]);
            }
        return studentClassesComboboxmodel;
        
    } catch (IOException e){
        e.printStackTrace();
    } 
        return null;
}
    
    public StudentRegistryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentNameLabel = new javax.swing.JLabel();
        studentNameText = new javax.swing.JTextField();
        studentSurnameLabel = new javax.swing.JLabel();
        studentSurnameText = new javax.swing.JTextField();
        studentNumberLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        studentDepartmentLabel = new javax.swing.JLabel();
        studentDepartmentText = new javax.swing.JTextField();
        studentClassesLabel = new javax.swing.JLabel();
        studentClassesCombobox = new javax.swing.JComboBox<>();
        studentNumberText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Öğrenci Kayıt Formu");

        studentNameLabel.setText("Öğrenci Adı:");

        studentSurnameLabel.setText("Öğrenci Soyadı:");

        studentNumberLabel.setText("Öğrenci No:");

        saveButton.setText("Kaydet");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        studentDepartmentLabel.setText("Öğrenci Bölümü: ");

        studentClassesLabel.setText("Öğrenci Dersleri:");

        studentClassesCombobox.setModel(loadDataFromFile().getModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentClassesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentDepartmentText, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(studentNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(studentSurnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(studentClassesCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentNumberText))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {studentClassesLabel, studentDepartmentLabel, studentNameLabel, studentNumberLabel, studentSurnameLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {studentDepartmentText, studentNameText, studentSurnameText});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNumberLabel)
                    .addComponent(studentNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentSurnameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentDepartmentLabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentClassesLabel)
                    .addComponent(studentClassesCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {studentClassesLabel, studentDepartmentLabel, studentNameLabel, studentSurnameLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {studentDepartmentText, studentNameText, studentSurnameText});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // method for saving inputs to the csv file
    private void saveToCSV(OgrenciClass ogrenci) {
        String fileName = "student_data.csv";
        boolean isFileEmpty = false;
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
        // Read the first line to check if the file has data
        String line = br.readLine();
        if (line == null || line.isEmpty())
        {
            isFileEmpty = true;
        }
        
        } catch (IOException e) {
            isFileEmpty = true;
        }
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true));) {
            
            // check for if the file is empty
            if (isFileEmpty){
                writer.write("Ogrenci No,Ogrenci Ad,Ogrenci Soyad,Ogrenci Bolum,Ogrenci Dersler");
                writer.newLine();
            }
            // Append data to the CSV file
            writer.write(ogrenci.getOgrenciNo() + "," + ogrenci.getOgrenciAd() + "," +
                    ogrenci.getOgrenciSoyad() + "," + ogrenci.getOgrenciBolum() + "," + ogrenci.getOgrenciDersler());
            writer.newLine();

            JOptionPane.showMessageDialog(this, "Bilgiler başarıyla kaydedildi", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Bilgileri dosyaya kaydederken hata oluştu", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // method for clearin the input fields
    private void clearFields(){
        studentNumberText.setText(null);
        studentNameText.setText(null);
        studentSurnameText.setText(null);
        studentDepartmentText.setText(null);
    }
    
    // method for save button action to save to csv file
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String studentNumber = studentNumberText.getText();
        String studentName = studentNameText.getText();
        String studentSurname = studentSurnameText.getText();
        String studentDepartment = studentDepartmentText.getText();
        String studentClasses = (String) studentClassesCombobox.getSelectedItem();

        // Check if any of the fields is empty
        if (studentNumber.isEmpty() || studentName.isEmpty() || studentSurname.isEmpty() || studentDepartment.isEmpty() || studentClasses == null) {
            JOptionPane.showMessageDialog(this, "Lütfen bütün boşlukları doldurunuz", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create a OgrenciClass instance
        OgrenciClass ogrenci = new OgrenciClass(studentNumber, studentName, studentSurname, studentDepartment, studentClasses);

        // Save data to CSV file
        saveToCSV(ogrenci);
        
        // Clear the text fields after the save
        clearFields();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> studentClassesCombobox;
    private javax.swing.JLabel studentClassesLabel;
    private javax.swing.JLabel studentDepartmentLabel;
    private javax.swing.JTextField studentDepartmentText;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JTextField studentNameText;
    private javax.swing.JLabel studentNumberLabel;
    private javax.swing.JTextField studentNumberText;
    private javax.swing.JLabel studentSurnameLabel;
    private javax.swing.JTextField studentSurnameText;
    // End of variables declaration//GEN-END:variables

    // Class for the StudentRegistryForm input fields
    private static class OgrenciClass {

        // variable of the class
        private String ogrenciNo;
        private String ogrenciAd;
        private String ogrenciSoyad;
        private String ogrenciBolum;
        private String ogrenciDersler;
                
        // constructor of the Class
        public OgrenciClass(String ogrenciNo, String ogrenciAd, String ogrenciSoyad, String ogrenciBolum, String ogrenciDersler) {
            this.ogrenciNo = ogrenciNo;
            this.ogrenciAd = ogrenciAd;
            this.ogrenciSoyad = ogrenciSoyad;
            this.ogrenciBolum = ogrenciBolum;
            this.ogrenciDersler = ogrenciDersler;
        }
        
        // get method for the ogrenciNo variable
        private String getOgrenciNo() {
            return ogrenciNo;
        }

        // get method for the ogrenciAd variable
        private String getOgrenciAd() {
            return ogrenciAd;
        }
        
        // get method for the ogrenciSoyad variable
        private String getOgrenciSoyad() {
            return ogrenciSoyad;
        }

        // get method for the ogrenciBolum variable
        private String getOgrenciBolum() {
            return ogrenciBolum;
        }
        
        // get method for the ogrenciDersler variable
        private String getOgrenciDersler() {
            return ogrenciDersler;
        }
        
    }
}
